export const PERMISSIONS = {
  PRODUCT_VIEW: "product.view",
  PRODUCT_CREATE: "product.create",
  PRODUCT_EDIT: "product.edit",
  PRODUCT_DELETE: "product.delete",
  PRODUCT_PRICE: "product.price",
  PRODUCT_IMAGE: "product.image",
  INVENTORY_VIEW: "inventory.view",
  INVENTORY_EDIT: "inventory.edit",
  INVENTORY_RESTOCK_APPROVE: "inventory.restock.approve",
  EMPLOYEE_VIEW: "employee.view",
  EMPLOYEE_CREATE: "employee.create",
  EMPLOYEE_EDIT: "employee.edit",
  EMPLOYEE_DELETE: "employee.delete",
  PROMOTION_VIEW: "promotion.view",
  PROMOTION_CREATE: "promotion.create",
  PROMOTION_EDIT: "promotion.edit",
  PROMOTION_DELETE: "promotion.delete",
  SALE_CREATE: "sale.create",
  SALE_VIEW: "sale.view",
  REPORT_VIEW: "report.view",
  REPORT_DAILY: "report.daily",
  REPORT_TREND: "report.trend",
  REPORT_TOP_PRODUCTS: "report.top-products",
  REPORT_WEEKLY: "report.weekly",
};
